<a href="https://colab.research.google.com/github/URahul11/ML_23AG1A66I7/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list1 = [2, 4, 6, 8]
array1 = np.array(list1)

print(array1)

[2 4 6 8]


In [10]:

array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


In [7]:

array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:

array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [22]:
array1=np.array([2,5,7])
print(array1.dtype)

int64


In [11]:
print(array1.ndim)

1


In [13]:
print(array1.size)

3


In [14]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

print(array1.shape)

(2, 3)


In [17]:
array1 = np.array([6, 7, 8, 10, 13])

array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

print(array1.itemsize)
print(array2.itemsize)

8
4


In [16]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])

print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7f9abf555d80>
Data of array2 is:  <memory at 0x7f9abf575e50>


In [20]:
array1 = np.array([1, 3, 5, 7, 9])
print(array1[2])
print(array1[3])
print(array1[-1])

5
7
9


In [23]:
array1[1]=10
print(array1)

[ 2 10  7]


In [28]:

array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])



element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)


element2 = array1[2, 0]  # returns 3
print("1st Element of 3rd Row:",element2)

4th Element at 2nd Row: 15
1st Element of 3rd Row: 2


In [27]:
array1=np.array([2,5,6,4,9])
median=np.median(array1)
print(median)

5.0
